  <footer>
    <div class="footer-contact"><h3>Kontakt</h3></div>
    <div class="footer-social-media">
      <h3>Hitta mig</h3>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minima ullam nobis quod quam temporibus alias a cum iure impedit enim, id perferendis ex provident! Temporibus minus soluta et ipsum? Iste atque, fuga iure quod, quia dignissimos officia hic sit possimus, autem earum similique nesciunt. Ducimus voluptas illum quo magnam unde natus, quos veritatis repudiandae quidem voluptate ratione deleniti nihil, quae aspernatur, quaerat maiores cum? Earum minus fuga mollitia eos nam facilis tenetur accusamus. Praesentium repellat quibusdam, obcaecati reiciendis porro quidem corrupti illum laborum atque accusantium sapiente, nemo labore, nihil eum facere molestiae hic fugiat! Debitis quia distinctio aperiam quaerat fugit, qui voluptates ratione amet officiis autem quis, quisquam impedit asperiores. Quibusdam quod quis, quidem sapiente cumque aut quaerat, impedit aperiam labore quam tempora in ad ipsum placeat. Aspernatur, dolorem atque nostrum exercitationem dolor possimus beatae recusandae aut magni voluptatum, esse incidunt placeat animi rerum a quo fugit molestiae impedit quis! Inventore eos possimus eaque incidunt, labore voluptatem beatae quas commodi accusamus quod similique nemo perferendis, aliquid reprehenderit eum. Error consectetur quod at itaque perspiciatis nostrum ullam iusto! Ipsam nisi dolore dignissimos veniam tempore odio in! Neque minima aut minus laudantium cum, exercitationem harum optio provident totam, velit dolorum numquam. Veniam iusto explicabo eaque quo quae deserunt facere harum quasi natus inventore eos minus sed unde rem nesciunt, architecto placeat tenetur quaerat, voluptates in delectus laboriosam corrupti dolorem? Laboriosam, nisi aspernatur perferendis perspiciatis aliquid accusamus aperiam quos amet quidem, impedit qui non dolor quia odit, nobis commodi? Iure culpa modi ipsam?

      </p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus beatae ullam aliquam culpa? Officia, libero? Similique optio ex maiores architecto sequi quae placeat provident? Labore iure amet necessitatibus deserunt aspernatur incidunt voluptas aperiam minima adipisci, officiis quasi odio veniam odit repudiandae perferendis tempora quis accusamus iusto eos inventore. Ut culpa molestiae accusamus, tenetur fuga qui maiores minima est amet voluptates cum laboriosam laborum sit atque nostrum mollitia provident illum sint quasi distinctio dignissimos consequatur voluptatibus? Soluta ipsum quidem, fugiat voluptates libero nam enim velit consequuntur veritatis laborum assumenda quibusdam, laboriosam maxime doloremque dolor ducimus fuga nihil accusamus quod veniam? Maxime omnis laboriosam veritatis dicta consequuntur eum similique error architecto ab veniam itaque odit quaerat esse consequatur at nihil necessitatibus provident molestias possimus ipsum, sint ullam sequi. Odio praesentium reprehenderit eius quisquam facilis qui dolor, magni porro vitae distinctio doloremque ullam mollitia, provident modi? Atque saepe nemo ab distinctio tempora, labore dicta officia sequi deserunt in velit asperiores tempore eaque fugiat ratione aperiam molestiae odio laudantium facere. Provident, incidunt. Ex, quaerat? Harum facere molestias quos quisquam enim commodi at sed. Reprehenderit perspiciatis ad molestiae. Suscipit laudantium eveniet quam reiciendis ut adipisci atque aperiam nulla similique nisi debitis, beatae corporis tempore exercitationem eius porro cumque inventore incidunt! Eligendi voluptate minus vitae accusamus facere id ducimus culpa repellat, doloremque quidem doloribus ratione dolores earum voluptatem atque harum, quis possimus quisquam tempore? Repellat, aliquid.</p>
    </div>
    <div class="">
      <i class="fab fa-unsplash"></i><i class="fab fa-font-awesome"></i></div>
    <button id="up-btn" onClick=upp()><i class="fas fa-caret-up up-icon"></i> Upp</button>
  </footer>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="javaScript/javascript.js"></script>
<script src="javaScript/script2.js"></script>
</body>
</html>